name: execute reusable workflow

on:
  workflow_dispatch:
    inputs:
        selection:
          description: "Selecciona una opción"
          required: true
          type: choice
          default: DEV
          options:
            - DEV
            - PRE
            - PRO

jobs:
  call-workflow-passing-data:
    uses: Sgomez04/ReusableWorkflows/.github/workflows/reusable.yml@main
    with:
      env: ${{ inputs.selection }}